### PR TITLE
Entity compatibility

### LINKED ISSUE #44: Validation inside model do not work
Using lotus-utils 0.3.3
Using sequel 4.18.0
Using lotus-model 0.2.0
Using lotus-validations 0.2.2

```ruby
require 'lotus/model'
require 'lotus/validations'

class Product
  include Lotus::Entity
  include Lotus::Validations

  attributes :name
  validates :name, type: String, presence: true
end

class ProductRepository
  include Lotus::Repository
end

Lotus::Model.configure do
  adapter type: :memory, uri: 'memory://localhost/test'

  mapping do
    collection :products do
      entity     Product
      repository ProductRepository

      attribute :id,   Integer
      attribute :name, String
    end
  end
end

Mutex.new.synchronize do
  Lotus::Model.load!
end

p = ProductRepository.create(Product.new(name: 'foo'))
r = ProductRepository.find(p.id)
ProductRepository.delete(r)

bundle exec ruby test.rb
/Users/gotar/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/lotus-validations-0.2.2/lib/lotus/validations/validation_set.rb:61:in `validate_options!': Unknown validation(s): type for "name" attribute (ArgumentError)
	from /Users/gotar/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/lotus-validations-0.2.2/lib/lotus/validations/validation_set.rb:32:in `add'
	from /Users/gotar/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/lotus-validations-0.2.2/lib/lotus/validations.rb:116:in `validates'
	from test.rb:9:in `<class:Product>'
	from test.rb:4:in `<main>'
```

### PR DESCRIPTION
**Pull request by jodosha**
Closes #44 

Ref https://github.com/lotus/model/pull/140

/cc @joneslee85

### CODE REVIEW

File: test/integration/lotus_entity_compatibility_test.rb [hunk 1]
```diff
@@ -0,0 +1,114 @@
+require 'test_helper'
+require 'lotus/model'
+
+describe 'lotus::entity compatibility' do
```
Comment (joneslee85) [inline test/integration/lotus_entity_compatibility_test.rb]: _nitpick_ upcase Lotus::Entity

**Comment by joneslee85** [comment]
:+1:
